//
// Created by Vlad Nitu on 29.08.2022.
//

#ifndef KICKSTART3_2022_SHERLOCKANDWATSONGYMSECRETS_H
#define KICKSTART3_2022_SHERLOCKANDWATSONGYMSECRETS_H
void solve_gym_secrets();
#endif //KICKSTART3_2022_SHERLOCKANDWATSONGYMSECRETS_H
